---
AWSTemplateFormatVersion: 2010-09-09

Description: Stack will create AWS resources to test Amazon FSx for Windows File Server in an isolated test environment.

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description: 'Copyright 2018 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Virtual Private Cloud
      Parameters:
        - VpcCidr
        - AvailabilityZones
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones (select 1)
      VpcCidr:
        default: VPC CIDR

Parameters:
  AvailabilityZones:
    Description: Select one (1) Availability Zone. One public subnet will be created.
    Type: AWS::EC2::AvailabilityZone::Name
  VpcCidr:
    AllowedValues: 
    - 10.0.0.0/16
    - 172.31.0.0/16
    - 192.168.0.0/16
    Default: 10.0.0.0/16
    Description: Select the private IPv4 CIDR for the VPC.
    Type: String

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZones:
          !Ref AvailabilityZones
        VpcCidr:
          !Ref VpcCidr
      TemplateURL: https://s3.amazonaws.com/aws-us-east-1/fsx-workshop/lustre/current/templates/FSx_CreateVPC.yaml
    
Outputs:
  Vpc:
    Value: !GetAtt [ Vpc, Outputs.Vpc ]
  VpcCidr: 
    Value: !GetAtt [ Vpc, Outputs.VpcCidr ]
  DefaultSecurityGroup:
    Value: !GetAtt [ Vpc, Outputs.DefaultSecurityGroup ]
  PublicSubnet0:
    Value: !GetAtt [ Vpc, Outputs.PublicSubnet0 ]
  PublicSubnet0Cidr:
    Value: !GetAtt [ Vpc, Outputs.PublicSubnet0Cidr ]
