---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates AWS resources to test Amazon FSx for Windows File Server.

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description: 'Copyright 2019 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Virtual Private Cloud
      Parameters:
        - VpcCidr
        - AvailabilityZones
        - ExternalAccessCidr
    - Label:
        default: Active Directory
      Parameters:
        - MadDnsName
        - MadEdition
    - Label:
        default: FSx for Windows File Server
      Parameters:
        - FileSystemName
        - StorageCapacity
        - ThroughputCapacity
        - SubnetId
        - SecurityGroupId
        - ActiveDirectoryId
        - DailyAutomaticBackupStartTime
        - CopyTagsToBackups
        - AutomaticBackupRetentionDays
        - WeeklyMaintenanceStartTime
    - Label:
        default: Clients
      Parameters:
        - KeyName
        - NssInstanceType
        - WinInstanceType
        - LinInstanceType  
    ParameterLabels:
      AutomaticBackupRetentionDays:
        default: Backup retention days
      AvailabilityZones:
        default: Availability Zones
      CopyTagsToBackups:
        default: Copy tags to backups (optional)
      DailyAutomaticBackupStartTime:
        default: Daily backup start time (optional)
      ExternalAccessCidr:
        default: External Access CIDR Block
      FileSystemName:
        default: File System Name
      KeyName:
        default: EC2 key pair
      LinInstanceType:
        default: Linux Server Instance Type
      MadDnsName:
        default: Directory DNS Name
      MadEdition:
        default: Directory Edition
      NssInstanceType:
        default: DFS Namespace Server Instance Type
      StorageCapacity:
        default: Storage capacity (GiB)
      ThroughputCapacity:
        default: Throughput capacity (MiB/s)
      VpcCidr:
        default: VPC CIDR
      WeeklyMaintenanceStartTime:
        default: Weekly maintenance start time (optional)
      WinInstanceType:
        default: Windows Server Instance Type

Parameters:
  AutomaticBackupRetentionDays:
    Default: 7
    Description: Number of days to retain automatic daily backups (0 to 35 days)
    MaxValue: 35
    MinValue: 0
    Type: Number
  AvailabilityZones:
    Description: Select two (2) Availability Zones. One public subnet will be created in each.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  CopyTagsToBackups:
    AllowedValues:
    - '' 
    - true
    - false
    Default: ''
    Description: Stripe set of the files imported from a data repository
    Type: String
  DailyAutomaticBackupStartTime:
    AllowedPattern: ^$|([01]\d|2[0-3]):?([0-5]\d)$
    Description: Enter the daily automatic backup start time in hour:minute UTC format (e.g. 11:30pm = 23:30)
    Type: String
  ExternalAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0
    Description: The CIDR IP range that is permitted to access the instances. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
  FileSystemName:
    Default: fsx-windows-workshop
    AllowedPattern: ^$|(.*)$
    Description: Name of file system - name value of key-value pair
    Type: String
  KeyName:
    Description: An existing Amazon EC2 key pair
    Type: AWS::EC2::KeyPair::KeyName
  LinInstanceType:
    AllowedValues: 
    - t3.large
    - t3.xlarge
    - c5.large
    - c5.xlarge
    - m5.large
    - m5.xlarge
    Default: c5.large
    Description: Amazon EC2 instance type - Linux server
    Type: String
  NssInstanceType:
    AllowedValues: 
    - t3.small
    - m5.large
    Default: t3.small
    Description: Amazon EC2 instance type - DFS Namespace servers
    Type: String
  WinInstanceType:
    AllowedValues: 
    - t3.large
    - t3.xlarge
    - c5.large
    - c5.xlarge
    - m5.large
    - m5.xlarge
    Default: c5.large
    Description: Amazon EC2 instance type - Windows server
    Type: String
  MadDnsName:
    Default: example.com
    Description: A fully qualified domain name. This name will resolve inside your VPC only. It does not need to be publicly resolvable (e.g. corp.example.com)
    Type: String
  MadEdition:
    AllowedValues: 
    - Standard
    - Enterprise
    Default: Standard
    Description: Standard or Enterprise edition of Microsoft Active Directory
    Type: String
  StorageCapacity:
    Default: 300
    Description: Storage capacity (GiB)
    MaxValue: 64000
    MinValue: 300
    Type: Number
  ThroughputCapacity:
    AllowedValues:
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    Default: 64
    Description: Throughput capacity (MiB/s)
    Type: String
  VpcCidr:
    AllowedValues: 
    - 10.0.0.0/16
    - 173.31.0.0/16
    - 192.168.0.0/16
    Default: 10.0.0.0/16
    Description: Select the private IPv4 CIDR for the VPC.
    Type: String
  WeeklyMaintenanceStartTime:
    AllowedPattern: ^$|[1-7]:([01]\d|2[0-3]):?([0-5]\d)$
    Description: Enter the weekly maintenance start time in day:hour:minute UTC format (e.g. Monday 11:30pm = 1:23:30)
    Type: String

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZones:
          !Join [ ',', !Ref AvailabilityZones ]
        VpcCidr:
          !Ref VpcCidr
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/01-vpc.yaml
  Sg:
    DependsOn: [ Vpc ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExternalAccessCidr:
          !Ref ExternalAccessCidr
        VpcId:
          !GetAtt [ Vpc, Outputs.Vpc ]
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/02-security-groups.yaml
  Mad:
    DependsOn: [ Sg ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        MadDnsName:
          !Ref MadDnsName
        MadEdition:
          !Ref MadEdition
        SubnetIds:
          !Join [ ',', [ !GetAtt [ Vpc, Outputs.PublicSubnet0 ], !GetAtt [ Vpc, Outputs.PublicSubnet1 ] ] ]
        VpcId:
          !GetAtt [ Vpc, Outputs.Vpc ]
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/03-active-directory.yaml
  Fsx:
    DependsOn: [ Mad ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DirectoryId:
          !GetAtt [ Mad, Outputs.DirectoryId ]
        AutomaticBackupRetentionDays:
          !Ref AutomaticBackupRetentionDays
        CopyTagsToBackups:
          !Ref CopyTagsToBackups
        DailyAutomaticBackupStartTime:
          !Ref DailyAutomaticBackupStartTime
        FileSystemName:
          !Ref FileSystemName
        SecurityGroupId:
          !GetAtt [ Sg, Outputs.FsxSecurityGroup ]
        StorageCapacity:
          !Ref StorageCapacity
        SubnetId:
          !GetAtt [ Vpc, Outputs.PrivateSubnet0 ]
        ThroughputCapacity:
          !Ref ThroughputCapacity
        WeeklyMaintenanceStartTime:
          !Ref WeeklyMaintenanceStartTime
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/04-fsx-windows.yaml
  Lin:
    DependsOn: [ Fsx ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        InstanceType:
          !Ref LinInstanceType
        KeyName:
          !Ref KeyName
        SecurityGroups:
          !GetAtt [ Sg, Outputs.ExternalAccessSecurityGroup ]
        Subnets:
          !GetAtt [ Vpc, Outputs.PublicSubnet0 ]
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/05-linux-instance.yaml
  Nss:
    DependsOn: [ Lin ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DirectoryId:
          !GetAtt [ Mad, Outputs.DirectoryId ]
        InstanceType:
          !Ref NssInstanceType
        KeyName:
          !Ref KeyName
        SecurityGroup:
          !GetAtt [ Sg, Outputs.ExternalAccessSecurityGroup ]
        Subnet:
          !Join [ ',', [ !GetAtt [ Vpc, Outputs.PublicSubnet0 ], !GetAtt [ Vpc, Outputs.PublicSubnet1 ] ] ]
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/06-namespace-servers.yaml
  Win:
    DependsOn: [ Nss ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DirectoryId:
          !GetAtt [ Mad, Outputs.DirectoryId ]
        InstanceType:
          !Ref WinInstanceType
        KeyName:
          !Ref KeyName
        SecurityGroup:
          !GetAtt [ Sg, Outputs.ExternalAccessSecurityGroup ]
        Subnets:
          !GetAtt [ Vpc, Outputs.PublicSubnet0 ]
      TemplateURL: https://s3.amazonaws.com/amazon-fsx/workshop/windows/07-windows-instance.yaml



