---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an AWS Managed Microsoft Active Directory

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Directory
      Parameters:
        - MadDnsName
    ParameterLabels:
      MadDnsName:
        default: Directory DNS Name

Parameters:
  MadDnsName:
    Default: example.com
    Description: A fully qualified domain name. This name will resolve inside your VPC only. It does not need to be publicly resolvable (e.g. example.com)
    Type: String

Resources:
  Password:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "admin@${MadDnsName}"}'
        GenerateStringKey: "password"
        PasswordLength: 32

Outputs:
  Username:
    Value: !Join [ "",[ "'{\"username\": \"admin@", !Ref MadDnsName, "\"}'" ] ]
  Username1:
    Value: !Sub '{"username": "admin@${MadDnsName}"}'
  Username2:
    Value:
      !Sub |
        '{"username": "admin@${MadDnsName}"}'