---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an AWS Managed Microsoft Active Directory

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Directory
      Parameters:
        - MadDnsName
        - MadEdition
    - Label:
        default: Amazon VPC
      Parameters:
        - VpcId
        - SubnetId
    ParameterLabels:
      MadDnsName:
        default: Directory DNS Name
      MadEdition:
        default: Directory Edition
      SubnetId:
        default: Subnet ID
      VpcId:
        default: VPC ID

Parameters:
  MadDnsName:
    Default: example.com
    Description: A fully qualified domain name. This name will resolve inside your VPC only. It does not need to be publicly resolvable (e.g. example.com)
    Type: String
  MadEdition:
    AllowedValues: 
    - Standard
    - Enterprise
    Default: Standard
    Description: Select the edition of Microsoft Active Directory
    Type: String
  SubnetId:
    Description: Select two subnets in the VPC above
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Description: Select the VPC
    Type: AWS::EC2::VPC::Id

Resources:
  Directory: 
    DependsOn: Password
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      Edition:
        !Ref MadEdition
      Name:
        !Ref MadDnsName
      Password:
        !Join ['', ['{{resolve:secretsmanager:', !Ref Password, ':SecretString:password}}' ]]
      VpcSettings: 
        SubnetIds: 
          - !Select [ 0, !Ref SubnetId ]
          - !Select [ 1, !Ref SubnetId ]
        VpcId: 
          !Ref VpcId
  Password:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "admin@${MadDnsName}"}'
        GenerateStringKey: "password"
        PasswordLength: 32
  DhcpOptions:
    Type: AWS::EC2::DHCPOptions
    Properties: 
      DomainName: !Ref MadDnsName
      DomainNameServers: !GetAtt Directory.DnsIpAddresses
  DhcpOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties: 
      DhcpOptionsId: !Ref DhcpOptions
      VpcId: !Ref VpcId

Outputs:
  DirectoryId:
    Value: !Ref Directory
  SecretId:
    Value: !Ref Password

