---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Amazon FSx for Windows File Server

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: File system configuration
      Parameters:
        - FileSystemName
        - StorageCapacity
        - ThroughputCapacity
        - SubnetId
        - SecurityGroupId
        - DirectoryId
    ParameterLabels:
      DirectoryId:
        default: Directory
      FileSystemName:
        default: File system name
      SecurityGroupId:
        default: Security group
      StorageCapacity:
        default: Storage capacity (GiB)
      SubnetId:
        default: Subnet
      ThroughputCapacity:
        default: Throughput capacity (MiB/s)

Parameters:
  DirectoryId:
    AllowedPattern: ^d-[0-9a-f]{10}$
    Description: Enter the directory ID of the AWS Managed Microsoft Active Directory (e.g. d-0123456789)
    Type: String    
  FileSystemName:
    Default: fsx-windows-workshop
    AllowedPattern: ^$|(.*)$
    Description: Name of file system - name value of key-value pair
    Type: String     
  SecurityGroupId:
    Description: Select an existing security group id
    Type: AWS::EC2::SecurityGroup::Id          
  StorageCapacity:
    Default: 300
    Description: Storage capacity (GiB)
    MaxValue: 64000
    MinValue: 300
    Type: Number
  SubnetId:
    Description: Select an existing subnet id
    Type: AWS::EC2::Subnet::Id
  ThroughputCapacity:
    AllowedValues:
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    Default: 64
    Description: Throughput capacity (MiB/s)
    Type: String

Resources:
  WindowsFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: WINDOWS
      StorageCapacity: !Ref StorageCapacity
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref FileSystemName
      WindowsConfiguration:
        ActiveDirectoryId: !Ref DirectoryId
        ThroughputCapacity: !Ref ThroughputCapacity

Outputs:
  FileSystemId:
    Value: !Ref WindowsFileSystem
