---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Amazon FSx for Lustre

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: File system configuration
      Parameters:
        - FileSystemName
        - StorageCapacity
        - SubnetId
        - SecurityGroupId
        - ImportPath
    ParameterLabels:
      ImportPath:
        default: Import path
      FileSystemName:
        default: Name tag value
      SecurityGroupId:
        default: Security group
      StorageCapacity:
        default: Storage capacity (GiB)
      SubnetId:
        default: Subnet

Parameters:
  ImportPath:
    AllowedPattern: ^$|(s3://)([a-z0-9.-]*)$
    Default: s3://nasanex
    Description: Import path e.g. s3://my-bucket/import-prefix
    Type: String
  FileSystemName:
    AllowedPattern: ^$|([A-Za-z0-9+-=._:/ ]{0,256})$
    Default: "Amazon FSx for Lustre 0"
    Description: Name of file system - name value of key-value pair
    Type: String     
  SecurityGroupId:
    Description: Select an existing security group id
    Type: AWS::EC2::SecurityGroup::Id          
  StorageCapacity:
    Default: 7200
    Description: Storage capacity of file system in increments of 3600 GiBs
    MaxValue: 100200
    MinValue: 3600
    Type: Number
  SubnetId:
    Description: Select an existing subnet id
    Type: AWS::EC2::Subnet::Id

Resources:
  FileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      StorageCapacity: !Ref StorageCapacity
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref FileSystemName
      LustreConfiguration:
        ImportPath: !Ref ImportPath

Outputs:
  FileSystemId:
    Value: !Ref FileSystem
