---
AWSTemplateFormatVersion: 2010-09-09

Description: Setup AWS Managed Microsoft Active Directory

Metadata:

  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description: 'Copyright 2018 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Directory
      Parameters:
        - MadDnsName
        - MadEdition
        - MadAdminPassword
    - Label:
        default: Amazon VPC
      Parameters:
        - VpcId
        - SubnetIds
    ParameterLabels:
      MadAdminPassword:
        default: Admin Password
      MadDnsName:
        default: Directory DNS Name
      MadEdition:
        default: Directory Edition
      SubnetIds:
        default: Subnet Ids
      VpcId:
        default: VPC Id

Parameters:

  MadAdminPassword:
    Description: The password for the default administrative user named Admin.
    Type: String
    NoEcho: true
  MadDnsName:
    Description: A fully qualified domain name. This name will resolve inside your VPC only. It does not need to be publicly resolvable (e.g. corp.example.com)
    Type: String
  MadEdition:
    AllowedValues: 
    - Standard
    - Enterprise
    Default: Enterprise
    Description: Standard or Enterprise edition of Microsoft Active Directory
    Type: String
  SubnetIds:
    Description: Select two existing subnets.
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Description: Select an existing VPC.
    Type: AWS::EC2::VPC::Id

Resources:
  
  Directory: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      Edition:
        !Ref MadEdition
      Name:
        !Ref MadDnsName
      Password: 
        !Ref MadAdminPassword
      VpcSettings: 
        SubnetIds: 
          - !Select [ 0, !Ref SubnetIds ]
          - !Select [ 1, !Ref SubnetIds ]
        VpcId: 
          !Ref VpcId

Outputs:
  
  DirectoryId:
    Value: !Ref Directory
  MadDnsName:
    Value: !Ref MadDnsName
